--Players
TRUNCATE TABLE players CASCADE;

TRUNCATE TABLE events CASCADE;

TRUNCATE TABLE fields CASCADE;

TRUNCATE TABLE groups CASCADE;

TRUNCATE TABLE ranks CASCADE;

TRUNCATE TABLE ratings CASCADE;

TRUNCATE TABLE teams CASCADE;