--Players
TRUNCATE TABLE players CASCADE;
ALTER SEQUENCE players_id_seq RESTART WITH 1;

TRUNCATE TABLE events CASCADE;
ALTER SEQUENCE events_id_seq RESTART WITH 1;

TRUNCATE TABLE fields CASCADE;
ALTER SEQUENCE fields_id_seq RESTART WITH 1;

TRUNCATE TABLE groups CASCADE;
ALTER SEQUENCE groups_id_seq RESTART WITH 1;

TRUNCATE TABLE ranks CASCADE;
ALTER SEQUENCE ranks_id_seq RESTART WITH 1;

TRUNCATE TABLE ratings CASCADE;
ALTER SEQUENCE ratings_id_seq RESTART WITH 1;

TRUNCATE TABLE teams CASCADE;
ALTER SEQUENCE teams_id_seq RESTART WITH 1;

TRUNCATE TABLE photos CASCADE;
ALTER SEQUENCE photos_id_seq RESTART WITH 1;
